# Site settings
title: Paul-Frederik Schubert
description: Personal blog and website
url: "https://PaulSchubert.github.io"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:title/

# These plugins work with GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag